name: Daily Internship Sync

on:
  push:
    branches:              # Triggers sync everytime the upstream repo is updated
      - main
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

jobs:
  sync-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache hash file
        uses: actions/cache@v3
        with:
          path: last_hash.txt
          key: internship-hash-${{ github.run_id }}
          restore-keys: |
            internship-hash-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create credentials file
        run: |
          echo "${{ secrets.GOOGLE_SHEET_CREDS }}" | base64 -d > credentials.json
          echo "Credentials file created successfully"

      - name: Run internship automation
        env:
          GOOGLE_SPREADSHEET_LINK: ${{ secrets.GOOGLE_SPREADSHEET_LINK }}
        run: python main.py

      - name: Save hash file to cache
        uses: actions/cache/save@v3
        if: always()
        with:
          path: last_hash.txt
          key: internship-hash-${{ github.run_id }}
